;;
;; This file contains DNS reverse lookup records for customers VLAN interfaces
;;
;; WARNING: this file is automatically generated using the
;; api/v4/dns/arpa API call to IXP Manager. Any local changes made to
;; this script will be lost.
;;
;; VLAN id: <?= $t->vlan->id ?>; tag: <?= $t->vlan->number ?>; name: <?= $t->vlan->name ?>.
;;
;; Generated: <?= now()->format( 'Y-m-d H:i:s' ) . "\n" ?>
;;

@               IN      SOA     quartz.alioth.systems.     noc.fix-berlin.net. (
                        <?= time() ?>      ; Serial
                        43200           ; Refresh
                        7200            ; Retry
                        1209600         ; Expire
                        7200            ; Minimum
            )
        IN      NS      quartz.alioth.systems. 
        IN      NS      virtue.gblon01.alioth.systems.
<?php foreach( $t->arpa as $a ): ?>
<?= trim($a['arpa']) ?>    IN      PTR     <?= trim($a['hostname']) ?>.
<?php endforeach; ?>
;; END
