;;
;; This file contains DNS forward lookup records for customers VLAN interfaces
;;
;; WARNING: this file is automatically generated using the
;; api/v4/dns/arpa API call to IXP Manager. Any local changes made to
;; this script will be lost.
;;
;; VLAN id: <?= $t->vlan->id ?>; tag: <?= $t->vlan->number ?>; name: <?= $t->vlan->name ?>.
;;
;; Generated: <?= now()->format( 'Y-m-d H:i:s' ) . "\n" ?>
;;
<?php foreach( $t->arpa as $a ): ?>
<?php if (str_ends_with($a['hostname'], ".peer.fix-berlin.net")): ?>
<?php if ($t->protocol == 4): ?>
<?= trim($a['hostname']) ?>.    IN      A     <?= trim($a['address']) ?>
<?php else if ($t->protocol == 6): ?>
<?= trim($a['hostname']) ?>.    IN      AAAA  <?= trim($a['address']) ?>
<?php else: ?>
;; Unknown protocol '<?= $t->protocol ?>', record skipped
<?php endif; ?>
<?php endif; ?>
<?php endforeach; ?>
;; END
